CREATE TABLE IF NOT EXISTS refresh_token(
    id BIGINT PRIMARY KEY AUTO_INCREMENT,
    user_id BIGINT,
    token VARCHAR(36),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expired_at TIMESTAMP,
    FOREIGN KEY(user_id) REFERENCES user(id)
)